INITIAL_PRODUCTS = [
    "I R 20	 (  1   )",			
    "அச்சு வெல்லம் (2	Jaggery block / Molded jaggery	Achchu Vellam)",
    "அடை மாவு (3	Adai flour	Adai Maavu)",
    "உடைத்த உளுந்து (4	Split black gram	Udaitha Ulundhu)",
    "உளுந்தங்களி மாவு (5	Urad dal porridge flour	Ulundhangali Maavu)",
    "கடலை மொச்சை (6	Field beans / Hyacinth beans	Kadalai Mochai)",
    "கம்பு அவுல் (7	Pearl millet flakes	Kambu Avul)",
    "கம்பு மாவு (8	Pearl millet flour	Kambu Maavu)",
    "கருப்பு உளுந்து (9	Black gram	Karuppu Ulundhu)",
    "கருப்பு கவுனி இடியாப்ப மாவு (10	Black Kavuni rice string hopper flour	Karuppu Kavuni Idyappam Maavu)",
    "கருப்பு கவுனி புட்டு மாவு (11	Black Kavuni rice puttu flour	Karuppu Kavuni Puttu Maavu)",
    "கருப்பு கொள்ளும் (12	Black horse gram	Karuppu Kollu)",
    "கருப்பு மொச்சை (13	Black field beans / Black hyacinth beans	Karuppu Mochai)",
    "கேழ்வரகு (14	Finger millet / Ragi	Kezhvaragu)",
    "கேழ்வரகு அவுல் (15	Finger millet flakes / Ragi flakes	Kezhvaragu Avul)",
    "கேழ்வரகு மாவு (16	Finger millet flour / Ragi flour	Kezhvaragu Maavu)",
    "கைக்குத்தல் அரிசி (17	Hand-pounded rice	Kaikkuthal Arisi)",
    "கொள்ளு கஞ்சி மாவு (18	Horse gram porridge flour	Kollu Kanji Maavu)",
    "கோதுமை அவுல் (19	Wheat flakes	Kothumai Avul)",
    "கோதுமை மாவு (20	Wheat flour	Kothumai Maavu)",
    "சத்து மாவு (21	Health mix powder / Nutritious multigrain flour	Sathu Maavu)",
    "சம்பா கோதுமை குருணை (22	Samba wheat grits / Broken Samba wheat	Samba Kothumai Kurunai)",
    "சம்பா கோதுமை ரவை (23	Samba wheat semolina	Samba Kothumai Ravai)",
    "சிவப்பரிசி இடியாப்ப மாவு (24	Red rice string hopper flour	Sivapparisai Idyappam Maavu)",
    "சிவப்பரிசி குரலை (25	Red rice rava / Coarsely ground red rice	Sivapparisai Kuralai)",
    "சிவப்பரிசி புட்டு மாவு (26	Red rice puttu flour	Sivapparisai Puttu Maavu)",
    "சிவப்பு கவுனி அரிசி (27	Red Kavuni rice	Sivappu Kavuni Arisi)",
    "சிவப்பு கவுனி அவள் (28	Red Kavuni rice flakes	Sivappu Kavuni Avul)",
    "சிவப்பு காராமணி (29	Red cowpeas / Red lobia	Sivappu Kaaramani)",
    "சிவப்பு கெட்டி அவுல் (30	Thick red rice flakes	Sivappu Ketti Avul)",
    "சிவப்பு சோளம் (31	Red sorghum	Sivappu Cholam)",
    "சிவப்பு நைஸ் அவுல்  (32	Fine red rice flakes	Sivappu Nice Avul)",
    "சிவப்புக் கொள்ளும் (33	Red horse gram	Sivappu Kollu)",
    "சுண்டவத்தல் (34	Dried berries	Sundavathal)",
    "செம்பா கோதுமை குரலை  (35	Samba wheat rava / Coarsely ground Samba wheat	Semba Kothumai Kuralai)",
    "சோள அவுல் (36	Corn flakes / Sorghum flakes	Cholam Avul)",
    "சோள மாவு (37	Corn flour / Sorghum flour	Cholam Maavu)",
    "தஞ்சாவூர் பொன்னி (38	Thanjavur Ponni	Thanjavur Ponni)",
    "நரிப்பயறு (39	Moth bean	Narippayaru)",
    "நாட்டு மூக்கு கடலை (40	Country-style broad beans / Field beans	Naattu Mookku Kadalai)",
    "நாட்டுக் கம்பு (41	Country pearl millet	Naattu Kambu)",
    "பச்சரிசி இடியாப்ப மாவு (42	Raw rice string hopper flour	Pachcharisi Idyappam Maavu)",
    "பச்சரிசி புட்டு மாவு (43	Raw rice puttu flour	Pachcharisi Puttu Maavu)",
    "பட்டாணி பருப்பு (44	Split peas	Pattani Paruppu)",
    "பாசிப் பயிறு  (45	Green gram / Moong dal	Paasi Payiru)",
    "போர் மொச்சை (46	War beans	Por Mochai)",
    "மக்கா சோழ ரவை (47	Corn semolina / Corn rava	Makkachola Ravai)",
    "மட்ட சம்பா (48	Matta Samba	Matta Samba)",
    "மட்ட சம்பா குருணை (49	Matta Samba grits / Broken Matta Samba	Matta Samba Kurunai)",
    "மணத்தக்காளி வத்தல்  (50	Dried wonderberry / Dried black nightshade berries	Manathakkali Vathal)",
    "மாப்பிள்ளை சம்பா (51	Mappillai Samba	Mappillai Samba)",
    "மிதுக்கு வத்தல் (52	Mithuku Vathal	Midhukku Vathal)",
    "மூங்கில் அரிசி (53	Bamboo rice	Moongil Arisi)",
    "மோர் மிளகாய் (54	Buttermilk chillies	Mor Milagai)",
    "வெள்ளை கெட்டி அவுல் (55	Thick white rice flakes	Vellai Ketti Avul)",
    "வெள்ளை சோளம் (56	White sorghum	Vellai Cholam)",
    "வெள்ளை நைஸ் அவுல் (57	Fine white rice flakes	Vellai Nice Avul)",
    "வெள்ளை பொன்னி (58	White Ponni	Vellai Ponni)",
    "வெள்ளை மொச்சை (59	White field beans / White hyacinth beans	Vellai Mochai)",
    "வெள்ளைக காராமணி (60	White cowpeas / White lobia	Vellai Kaaramani"
]
SUGGESTIONS = INITIAL_PRODUCTS
